Repository jpbede/aioelectricitymaps, pull requests merged in 2024-02, with the labels that each got.

#96 Guard against non-200 HTTP responses
  aioelectricitymaps/__init__.py
  aioelectricitymaps/electricitymaps.py
  aioelectricitymaps/exceptions.py
  pyproject.toml
  tests/test_electricitymaps.py
Labels: enhancement, minor

#97 Add missing permissions to the lock workflow
  .github/workflows/lock.yml
Labels: ci

#100 Add buymeacoffee.com link
  .github/FUNDING.yml
Labels: maintenance

#103 Make zone key upper case in latest_carbon_intensity_by_country_code
  aioelectricitymaps/electricitymaps.py
Labels: bugfix

#107 Use right HTTP status code for invalid token response
  aioelectricitymaps/electricitymaps.py
  tests/test_electricitymaps.py
Labels: bugfix

#108 Allow API calls to be unauthenticated
  aioelectricitymaps/electricitymaps.py
Labels: new-feature

#109 Raise an error when API returned no data
  aioelectricitymaps/__init__.py
  aioelectricitymaps/const.py
  aioelectricitymaps/exceptions.py
  aioelectricitymaps/models.py
  tests/fixtures/no-data-response.json
  tests/fixtures/unknown-response.json
  tests/test_electricitymaps.py
Labels: enhancement

#119 Migrate to aioresponses in tests
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_electricitymaps.py
Labels: enhancement

#121 Use fixture for client
  tests/__snapshots__/test_electricitymaps.ambr
  tests/conftest.py
  tests/test_electricitymaps.py
Labels: enhancement

#122 Use aiohttp session timeout instead of asyncio.timeout
  aioelectricitymaps/electricitymaps.py
Labels: enhancement, minor
